[package]
name = "chapaty"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.26"
futures = "0.3.28"
google-cloud-default = {version = "0.4.0", features = ["storage"] }
google-cloud-storage = "0.13.0"
mockall = "0.11.4"
polars = {version = "0.31.1", features = ["lazy", "partition_by", "serde", "cum_agg"]}
rayon = "1.7.0"
regex = "1.9.1"
reqwest = "0.11.18"
serde = "1.0.175"
serde_json = "1.0.103"
strum = "0.25.0"
strum_macros = "0.25.1"
tokio = { version = "1.29.1", features = ["full"] }
